services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
    ControleOnline\:
        resource: '../../src/*'
        exclude: '../src/{DependencyInjection,Entity,Resource,Migrations,Library,Tests,Kernel.php}'
    ControleOnline\Repository\:
        resource: '../../src/Repository'
        tags: ['doctrine.repository_service']
        public: true
    ControleOnline\Controller\:
        resource: '../../src/Controller'
        tags: ['controller.service_arguments']
        public: true
    ControleOnline\Command\:
        resource: '../../src/Command'
        tags: ['console.command']
        public: true
    ControleOnline\Filter\:
        resource: '../../src/Filter'
        public: true